package com.fss.pos.host.iso8583.visa;

public class VisaMessageMap extends VisaMessage8583 {
	public VisaMessageMap() {
	}

	public byte[] pack() {
		return super.pack(VISAFIELDMAP);
	}

	public boolean unpack(String message) {
		return super.unpack(message, VISAFIELDMAP);
	}

	/**
	 * For all fields, the format can be: AN (alphanumeric, EBCDIC) ANS
	 * (alphanumeric/special characters, EBCDIC) B (binary value) BCD (numeric,
	 * 4-bit BCD = unsigned packed) Bit string N (numeric, 1 byte per character)
	 * indicated as 'T'
	 * 
	 * 
	 * Fieldlength indicates length of the data if length is fixed non negative
	 * value provided,zero indicates bit is not in use Fieldlength data type
	 * indicates 'B' - binary,'H'- Ascii , 'T' - Integer Bitdatatype indicates
	 * 'B' -binary , 'E' - EBCDIC Subelement indicates 'N' - No subelements ,
	 * 'S' - Yes sublements available
	 */

	private static final VisaField VISAFIELDMAP[] = {
			new VisaField("F-1", 8, 'I', 'I', 'N'),
			new VisaField("F-2", -2, 'B', 'B', 'N'),
			new VisaField("F-3", 6, 'B', 'B', 'N'),
			new VisaField("F-4", 12, 'B', 'B', 'N'),
			new VisaField("F-5", 12, 'B', 'B', 'N'),
			new VisaField("F-6", 12, 'B', 'B', 'N'),
			new VisaField("F-7", 10, 'B', 'B', 'N'),
			new VisaField("F-8", 8, 'B', 'B', 'N'),
			new VisaField("F-9", 8, 'B', 'B', 'N'),
			new VisaField("F-10", 8, 'B', 'B', 'N'),
			new VisaField("F-11", 6, 'B', 'B', 'N'),
			new VisaField("F-12", 6, 'B', 'B', 'N'),
			new VisaField("F-13", 4, 'B', 'B', 'N'),
			new VisaField("F-14", 4, 'B', 'B', 'N'),
			new VisaField("F-15", 4, 'B', 'B', 'N'),
			new VisaField("F-16", 4, 'B', 'B', 'N'),
			new VisaField("F-17", 4, 'T', 'B', 'N'),
			new VisaField("F-18", 4, 'B', 'B', 'N'),
			new VisaField("F-19", 3, 'B', 'B', 'N'),
			new VisaField("F-20", 3, 'B', 'B', 'N'),
			new VisaField("F-21", 0, 'B', 'B', 'N'),
			new VisaField("F-22", 4, 'B', 'B', 'N'),
			new VisaField("F-23", 3, 'B', 'B', 'N'),
			new VisaField("F-24", 3, 'B', 'B', 'N'),
			new VisaField("F-25", 2, 'B', 'B', 'N'),
			new VisaField("F-26", 2, 'B', 'B', 'N'),
			new VisaField("F-27", 0, 'B', 'B', 'N'),
			new VisaField("F-28", 9, 'B', 'E', 'N'),
			new VisaField("F-29", 0, 'B', 'E', 'N'),
			new VisaField("F-30", 0, 'B', 'E', 'N'),
			new VisaField("F-31", 0, 'B', 'E', 'N'),
			new VisaField("F-32", -2, 'B', 'B', 'N'),
			new VisaField("F-33", -2, 'B', 'B', 'N'),
			new VisaField("F-34", -2, 'B', 'B', 'N'),
			new VisaField("F-35", -2, 'B', 'B', 'N'),
			new VisaField("F-36", -2, 'B', 'B', 'N'),
			new VisaField("F-37", 12, 'H', 'E', 'N'),
			new VisaField("F-38", 6, 'H', 'E', 'N'),
			new VisaField("F-39", 2, 'H', 'E', 'N'),
			new VisaField("F-40", 0, 'H', 'E', 'N'),
			new VisaField("F-41", 8, 'H', 'E', 'N'),
			new VisaField("F-42", 15, 'H', 'E', 'N'),
			new VisaField("F-43", 40, 'H', 'E', 'N'),
			new VisaField("F-44", -2, 'H', 'E', 'S'),
			new VisaField("F-45", -2, 'H', 'E', 'N'),
			new VisaField("F-46", -2, 'H', 'E', 'N'),
			new VisaField("F-47", -2, 'H', 'E', 'N'),
			new VisaField("F-48", -2, 'H', 'E', 'N'),
			new VisaField("F-49", 3, 'B', 'B', 'N'),
			new VisaField("F-50", 3, 'B', 'B', 'N'),
			new VisaField("F-51", 3, 'B', 'B', 'N'),
			new VisaField("F-52", 16, 'B', 'B', 'N'),
			new VisaField("F-53", 16, 'B', 'B', 'N'),
			new VisaField("F-54", -2, 'H', 'E', 'N'),
			new VisaField("F-55", -2, 'T', 'B', 'N'),
			new VisaField("F-56", -2, 'H', 'E', 'N'),
			new VisaField("F-57", -2, 'H', 'E', 'N'),
			new VisaField("F-58", -2, 'H', 'E', 'N'),
			new VisaField("F-59", -2, 'H', 'E', 'N'),
			new VisaField("F-60", -2, 'T', 'B', 'S'),
			new VisaField("F-61", -2, 'T', 'B', 'N'),
			new VisaField("F-62", -2, 'T', 'B', 'S'),
			new VisaField("F-63", -2, 'T', 'B', 'S'),
			new VisaField("F-64", 8, 'B', 'B', 'N'),
			new VisaField("F-65", 0, 'I', 'I', 'N'),
			new VisaField("F-66", 1, 'T', 'B', 'N'),
			new VisaField("F-67", 0, 'T', 'B', 'N'),
			new VisaField("F-68", 3, 'T', 'B', 'N'),
			new VisaField("F-69", 0, 'B', 'B', 'N'),
			new VisaField("F-70", 3, 'T', 'B', 'N'),
			new VisaField("F-71", 0, 'B', 'B', 'N'),
			new VisaField("F-72", 0, 'B', 'B', 'N'),
			new VisaField("F-73", 6, 'T', 'B', 'N'),
			new VisaField("F-74", 10, 'T', 'B', 'N'),
			new VisaField("F-75", 10, 'T', 'B', 'N'),
			new VisaField("F-76", 10, 'T', 'B', 'N'),
			new VisaField("F-77", 10, 'T', 'B', 'N'),
			new VisaField("F-78", 0, 'T', 'B', 'N'),
			new VisaField("F-79", 0, 'T', 'B', 'N'),
			new VisaField("F-80", 0, 'B', 'B', 'N'),
			new VisaField("F-81", 0, 'B', 'B', 'N'),
			new VisaField("F-82", 0, 'B', 'B', 'N'),
			new VisaField("F-83", 0, 'B', 'B', 'N'),
			new VisaField("F-84", 0, 'B', 'B', 'N'),
			new VisaField("F-85", 0, 'B', 'B', 'N'),
			new VisaField("F-86", 16, 'T', 'B', 'N'),
			new VisaField("F-87", 16, 'T', 'B', 'N'),
			new VisaField("F-88", 16, 'T', 'B', 'N'),
			new VisaField("F-89", 16, 'T', 'B', 'N'),
			new VisaField("F-90", 42, 'T', 'B', 'N'),
			new VisaField("F-91", 1, 'H', 'E', 'N'),
			new VisaField("F-92", 2, 'H', 'E', 'N'),
			new VisaField("F-93", 0, 'H', 'E', 'N'),
			new VisaField("F-94", 0, 'B', 'E', 'N'),
			new VisaField("F-95", 42, 'H', 'E', 'N'),
			new VisaField("F-96", 16, 'B', 'B', 'N'),
			new VisaField("F-97", 17, 'H', 'E', 'N'),
			new VisaField("F-98", 0, 'H', 'E', 'N'),
			new VisaField("F-99", -2, 'B', 'B', 'N'),
			new VisaField("F-100", -2, 'B', 'B', 'N'),
			new VisaField("F-101", -2, 'H', 'E', 'N'),
			new VisaField("F-102", -2, 'H', 'E', 'N'),
			new VisaField("F-103", -2, 'H', 'E', 'N'),
			new VisaField("F-104", -2, 'H', 'B', 'N'),
			new VisaField("F-105", 32, 'B', 'B', 'N'),
			new VisaField("F-106", 0, 'B', 'B', 'N'),
			new VisaField("F-107", 0, 'B', 'B', 'N'),
			new VisaField("F-108", 0, 'B', 'B', 'N'),
			new VisaField("F-109", 0, 'B', 'B', 'N'),
			new VisaField("F-110", 0, 'B', 'B', 'N'),
			new VisaField("F-111", 0, 'B', 'B', 'N'),
			new VisaField("F-112", 0, 'B', 'B', 'N'),
			new VisaField("F-113", 0, 'B', 'B', 'N'),
			new VisaField("F-114", 0, 'B', 'B', 'N'),
			new VisaField("F-115", -2, 'H', 'E', 'N'),
			new VisaField("F-116", -2, 'H', 'B', 'N'),
			new VisaField("F-117", -2, 'H', 'E', 'N'),
			new VisaField("F-118", -2, 'H', 'E', 'N'),
			new VisaField("F-119", -2, 'H', 'E', 'N'),
			new VisaField("F-120", 0, 'T', 'B', 'N'),
			new VisaField("F-121", 0, 'H', 'E', 'N'),
			new VisaField("F-122", 0, 'H', 'E', 'N'),
			new VisaField("F-123", -2, 'H', 'E', 'N'),
			new VisaField("F-124", 0, 'H', 'E', 'N'),
			new VisaField("F-125", -2, 'H', 'E', 'N'),
			new VisaField("F-126", -2, 'T', 'B', 'S'),
			new VisaField("F-127", -2, 'B', 'B', 'N'),
			new VisaField("F-128", 0, 'H', 'B', 'N'),
			new VisaField("F-129", 8, 'B', 'B', 'N'),
			new VisaField("F-130", 24, 'B', 'B', 'N'),
			new VisaField("F-131", 40, 'B', 'B', 'N'),
			new VisaField("F-132", 4, 'B', 'B', 'N'),
			new VisaField("F-133", 8, 'H', 'E', 'N'),
			new VisaField("F-134", -1, 'T', 'B', 'N'),
			new VisaField("F-135", -1, 'T', 'B', 'N'),
			new VisaField("F-136", 16, 'H', 'B', 'N'),
			new VisaField("F-137", 4, 'H', 'B', 'N'),
			new VisaField("F-138", 16, 'H', 'B', 'N'),
			new VisaField("F-139", 20, 'H', 'B', 'N'),
			new VisaField("F-140", -1, 'T', 'B', 'N'),
			new VisaField("F-141", -1, 'T', 'B', 'N'),
			new VisaField("F-142", -1, 'T', 'B', 'N'),
			new VisaField("F-143", -1, 'T', 'B', 'N'),
			new VisaField("F-144", 2, 'B', 'B', 'N'),
			new VisaField("F-145", 3, 'B', 'B', 'N'),
			new VisaField("F-146", 6, 'B', 'B', 'N'),
			new VisaField("F-147", 12, 'B', 'B', 'N'),
			new VisaField("F-148", 3, 'B', 'B', 'N'),
			//new VisaField("F-149", 6, 'B', 'B', 'N'),//Para-DCC
			new VisaField("F-149", 12, 'B', 'B', 'N'),
			new VisaField("F-150", 8, 'B', 'B', 'N'),
			new VisaField("F-151", 12, 'B', 'B', 'N'),
			new VisaField("F-152", 8, 'H', 'B', 'N'),
			new VisaField("F-153", 2, 'B', 'B', 'N'),
			new VisaField("F-154", 1, 'B', 'B', 'N'),
			new VisaField("F-155", 1, 'B', 'B', 'N'),
			new VisaField("F-156", 9, 'B', 'B', 'N'),
			new VisaField("F-157", 9, 'B', 'B', 'N'),
			new VisaField("F-158", 9, 'B', 'B', 'N'),
			new VisaField("F-159", 9, 'B', 'B', 'N'),
			new VisaField("F-160", -1, 'B', 'B', 'N'),
			new VisaField("F-161", -1, 'B', 'B', 'N'),
			new VisaField("F-162", -1, 'B', 'B', 'N'),
			new VisaField("F-163", -1, 'B', 'B', 'N'),
			new VisaField("F-164", -1, 'B', 'B', 'N'),
			new VisaField("F-165", -2, 'B', 'B', 'N'),
			new VisaField("F-166", 6, 'B', 'B', 'N'),
			new VisaField("F-167", 2, 'B', 'B', 'N'),
			new VisaField("F-168", -3, 'B', 'B', 'N'),
			new VisaField("F-169", 8, 'B', 'B', 'N'),
			new VisaField("F-170", 15, 'B', 'B', 'N'),
			new VisaField("F-171", 40, 'B', 'B', 'N'),
			new VisaField("F-172", 20, 'B', 'B', 'N'),
			new VisaField("F-173", -1, 'B', 'B', 'N'),
			new VisaField("F-174", -1, 'B', 'B', 'N'),
			new VisaField("F-175", -1, 'B', 'B', 'N'),
			new VisaField("F-176", -1, 'B', 'B', 'N'),
			new VisaField("F-177", 3, 'B', 'B', 'N'),
			new VisaField("F-178", 3, 'B', 'B', 'N'),
			new VisaField("F-179", 3, 'B', 'B', 'N'),
			new VisaField("F-180", 16, 'B', 'B', 'N'),
			new VisaField("F-181", 16, 'B', 'B', 'N'),
			new VisaField("F-182", -2, 'B', 'B', 'N'),
			new VisaField("F-183", -1, 'H', 'E', 'N'),
			new VisaField("F-184", -1, 'B', 'B', 'N'),
			new VisaField("F-185", -1, 'B', 'B', 'N'),
			new VisaField("F-186", -1, 'B', 'B', 'N'),
			new VisaField("F-187", -1, 'H', 'E', 'N'),
			new VisaField("F-188", -1, 'B', 'B', 'N'),
			new VisaField("F-189", -2, 'B', 'B', 'N'),
			new VisaField("F-190", 10, 'B', 'B', 'N'),
			new VisaField("F-191", -2, 'B', 'B', 'N'),
			new VisaField("F-192", 8, 'B', 'B', 'N')

	};

	public static final VisaField VISAFIELDMAP44[] = {

	new VisaField("S-44.1", 1, 'N', 'E', 'N'),
			new VisaField("S-44.2", 1, 'N', 'E', 'N'),
			new VisaField("S-44.3", 0, 'N', 'N', 'N'),
			new VisaField("S-44.4", 0, 'N', 'N', 'N'),
			new VisaField("S-44.5", 1, 'N', 'E', 'N'),
			new VisaField("S-44.6", 2, 'N', 'E', 'N'),
			new VisaField("S-44.7", 1, 'N', 'E', 'N'),
			new VisaField("S-44.8", 1, 'N', 'E', 'N'),
			new VisaField("S-44.9", 0, 'N', 'N', 'N'),
			new VisaField("S-44.10", 1, 'N', 'E', 'N'),
			new VisaField("S-44.11", 2, 'N', 'E', 'N'),
			new VisaField("S-44.12", 1, 'N', 'E', 'N'),
			new VisaField("S-44.13", 1, 'N', 'E', 'N'),
			new VisaField("S-44.14", 4, 'N', 'E', 'N')

	};

	public static final VisaField VISAFIELDMAP60[] = {

	new VisaField("S-60.1", 1, 'N', 'T', 'N'),
			new VisaField("S-60.2", 1, 'N', 'T', 'N'),
			new VisaField("S-60.3", 1, 'N', 'T', 'N'),
			new VisaField("S-60.4", 1, 'N', 'T', 'N'),
			new VisaField("S-60.5", 2, 'N', 'T', 'N'),
			new VisaField("S-60.6", 1, 'N', 'T', 'N'),
			new VisaField("S-60.7", 1, 'N', 'T', 'N'),
			new VisaField("S-60.8", 2, 'N', 'T', 'N'),
			new VisaField("S-60.9", 1, 'N', 'T', 'N'),
			new VisaField("S-60.10", 1, 'N', 'T', 'N') };

	public static final VisaField VISAFIELDMAP62[] = {

	new VisaField("S-62.1", 1, 'N', 'E', 'N'),
			new VisaField("S-62.2", 15, 'N', 'T', 'N'),
			new VisaField("S-62.3", 4, 'N', 'E', 'N'),
			new VisaField("S-62.4", 1, 'N', 'E', 'N'),
			new VisaField("S-62.5", 2, 'N', 'T', 'N'),
			new VisaField("S-62.6", 1, 'N', 'E', 'N'),
			new VisaField("S-62.7", 26, 'N', 'E', 'N'),
			new VisaField("S-62.8", 6, 'N', 'T', 'N'),
			new VisaField("S-62.9", 1, 'N', 'E', 'N'),
			new VisaField("S-62.10", 6, 'N', 'T', 'N'),
			new VisaField("S-62.11", 2, 'N', 'T', 'N'),
			new VisaField("S-62.12", 2, 'N', 'T', 'N'),
			new VisaField("S-62.13", 1, 'N', 'E', 'N'),
			new VisaField("S-62.14", 12, 'N', 'T', 'N'),
			new VisaField("S-62.15", 1, 'N', 'E', 'N'),
			new VisaField("S-62.16", 2, 'N', 'E', 'N'),
			new VisaField("S-62.17", 15, 'N', 'E', 'N'),
			new VisaField("S-62.18", 1, 'N', 'E', 'N'),
			new VisaField("S-62.19", 2, 'N', 'E', 'N'),
			new VisaField("S-62.20", 10, 'N', 'T', 'N'),
			new VisaField("S-62.21", 4, 'N', 'E', 'N'),
			new VisaField("S-62.22", 6, 'N', 'E', 'N'),
			new VisaField("S-62.23", 2, 'N', 'E', 'N'),
			new VisaField("S-62.24", 6, 'N', 'E', 'N'),
			new VisaField("S-62.25", 1, 'N', 'E', 'N'),
			new VisaField("S-62.26", 1, 'N', 'E', 'N') };

	public static final VisaField VISAFIELDMAP63[] = {

	new VisaField("S-63.1", 4, 'N', 'B', 'N'),
			new VisaField("S-63.2", 4, 'N', 'B', 'N'),
			new VisaField("S-63.3", 4, 'N', 'B', 'N'),
			new VisaField("S-63.4", 4, 'N', 'B', 'N'),
			new VisaField("S-63.5", 0, 'N', 'N', 'N'),
			new VisaField("S-63.6", 7, 'N', 'E', 'N'),
			new VisaField("S-63.7", 0, 'N', 'N', 'N'),
			new VisaField("S-63.8", 8, 'N', 'B', 'N'),
			new VisaField("S-63.9", 14, 'N', 'E', 'N'),
			new VisaField("S-63.10", 13, 'N', 'E', 'N'),
			new VisaField("S-63.11", 1, 'N', 'E', 'N'),
			new VisaField("S-63.12", 30, 'N', 'E', 'N'),
			new VisaField("S-63.13", 6, 'N', 'B', 'N'),
			new VisaField("S-63.14", 36, 'N', 'E', 'N'),
			new VisaField("S-63.15", 9, 'N', 'E', 'N'),
			new VisaField("S-63.16", 0, 'N', 'N', 'N'),
			new VisaField("S-63.17", 0, 'N', 'N', 'N'),
			new VisaField("S-63.18", 2, 'N', 'B', 'N'),
			new VisaField("S-63.19", 3, 'N', 'E', 'N'),
			new VisaField("S-63.20", 0, 'N', 'N', 'N'),
			new VisaField("S-63.21", 1, 'N', 'E', 'N'),
			new VisaField("S-63.22", 0, 'N', 'N', 'N') };

	public static final VisaField VISAFIELDMAP126[] = {

	new VisaField("S-126.1", -2, 'H', 'E', 'N'),
			new VisaField("S-126.2", -2, 'H', 'E', 'N'),
			new VisaField("S-126.3", -2, 'H', 'E', 'N'),
			new VisaField("S-126.4", -2, 'H', 'E', 'N'),
			new VisaField("S-126.5", -2, 'B', 'B', 'N'),
			new VisaField("S-126.6", -2, 'B', 'B', 'N'),
			new VisaField("S-126.7", -2, 'B', 'B', 'N'),
			new VisaField("S-126.8", 40, 'B', 'B', 'N'),
			new VisaField("S-126.9", 40, 'B', 'B', 'N'),
			new VisaField("S-126.10", 6, 'H', 'E', 'N'),
			new VisaField("S-126.11", 0, 'N', 'N', 'N'),
			new VisaField("S-126.12", 6, 'B', 'B', 'N'),
			new VisaField("S-126.13", 1, 'H', 'E', 'N'),
			new VisaField("S-126.14", 0, 'H', 'E', 'N'),
			new VisaField("S-126.15", 1, 'H', 'E', 'N'),
			new VisaField("S-126.16", -2, 'H', 'E', 'N'),
			new VisaField("S-126.17", 0, 'N', 'N', 'N'),
			new VisaField("S-126.18", -2, 'H', 'E', 'N'),
			new VisaField("S-126.19", 1, 'H', 'E', 'N'),
			new VisaField("S-126.20", 0, 'N', 'N', 'N') };

}
